version: "3"
services:
  db:
    image: database
    container_name: database
    networks:
      my-network:
        ipv4_address: 172.16.238.10
        aliases:
          - mysql
  app:
    image: frontend
    container_name: frontend
    networks:
      my-network:
        ipv4_address: 172.16.238.20
        aliases:
          - webapp
    depends_on:
      - db
networks:
  my-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
